import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const montserrat = Montserrat({ subsets: ["latin"], display: "swap", adjustFontFallback: false});

export const metadata = {
  title: "KIVU ART & CONFORT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}  relative`}>
        <Navbar />
        {children}
        <div className="">
          <div className="xl:px-[3rem] lg:px-[3rem] md:px-[2rem] px-0">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
