// Données de produits
export const products = [
  // Tables
  {
    id: 1,
    name: "Table basse moderne",
    category: "tables",
    price: 50,
    image: "/images/Image 14.jpg",
    description: "Table basse design contemporain",
    stock: 5,
  },
  {
    id: 2,
    name: "Table en bois massif",
    category: "tables",
    price: 70,
    image: "/images/Image 34.jpg",
    description: "Table élégante en bois massif",
    stock: 3,
  },
  {
    id: 3,
    name: "Table de salle à manger",
    category: "tables",
    price: 65,
    image: "/images/Image 35.jpg",
    description: "Table spacieuse pour 6 personnes",
    stock: 2,
  },
  {
    id: 4,
    name: "Table haute de bar",
    category: "tables",
    price: 95,
    image: "/images/Image 36.jpg",
    description: "Table haute avec design épuré",
    stock: 4,
  },
  // Chaises
  {
    id: 5,
    name: "Chaise confortable",
    category: "chaises",
    price: 50,
    image: "/images/Image 16.jpg",
    description: "Chaise ergonomique avec rembourrage",
    stock: 8,
  },
  {
    id: 6,
    name: "Chaise design",
    category: "chaises",
    price: 30,
    image: "/images/Image 17.jpg",
    description: "Chaise minimaliste moderne",
    stock: 10,
  },
  {
    id: 7,
    name: "Chaise premium",
    category: "chaises",
    price: 45,
    image: "/images/Image 18.jpg",
    description: "Chaise haut de gamme avec structure solide",
    stock: 6,
  },
  {
    id: 8,
    name: "Chaise basique",
    category: "chaises",
    price: 20,
    image: "/images/Image 40.jpg",
    description: "Chaise simple et robuste",
    stock: 15,
  },
  // Canapés
  {
    id: 9,
    name: "Canapé 2 places",
    category: "canapes",
    price: 120,
    image: "/images/Image 14.jpg",
    description: "Canapé confortable pour deux personnes",
    stock: 3,
  },
  {
    id: 10,
    name: "Canapé 3 places",
    category: "canapes",
    price: 180,
    image: "/images/Image 34.jpg",
    description: "Canapé spacieux famille",
    stock: 2,
  },
  // Bureaux
  {
    id: 11,
    name: "Bureau exécutif",
    category: "bureaux",
    price: 200,
    image: "/images/Image 16.jpg",
    description: "Bureau en bois massif spacieux",
    stock: 4,
  },
  {
    id: 12,
    name: "Bureau compact",
    category: "bureaux",
    price: 85,
    image: "/images/Image 17.jpg",
    description: "Bureau pratique pour petit espace",
    stock: 6,
  },
  {
    id: 13,
    name: "Bureau gaming",
    category: "bureaux",
    price: 150,
    image: "/images/Image 18.jpg",
    description: "Bureau ergonomique avec rangements",
    stock: 5,
  },
  {
    id: 14,
    name: "Bureau enfant",
    category: "bureaux",
    price: 60,
    image: "/images/Image 40.jpg",
    description: "Bureau adapté pour enfants",
    stock: 7,
  },
  // Rangements
  {
    id: 15,
    name: "Bibliothèque 5 niveaux",
    category: "rangements",
    price: 110,
    image: "/images/Image 14.jpg",
    description: "Bibliothèque spacieuse en bois",
    stock: 3,
  },
  {
    id: 16,
    name: "Armoire dressing",
    category: "rangements",
    price: 250,
    image: "/images/Image 34.jpg",
    description: "Armoire grande capacité",
    stock: 2,
  },
  {
    id: 17,
    name: "Étagère murale",
    category: "rangements",
    price: 40,
    image: "/images/Image 35.jpg",
    description: "Étagère moderne et légère",
    stock: 10,
  },
  {
    id: 18,
    name: "Buffet de cuisine",
    category: "rangements",
    price: 180,
    image: "/images/Image 36.jpg",
    description: "Buffet élégant pour cuisine",
    stock: 2,
  },
];

export const categories = [
  { id: "all", name: "Tous les produits" },
  { id: "tables", name: "Tables" },
  { id: "chaises", name: "Chaises" },
  { id: "canapes", name: "Canapés" },
  { id: "bureaux", name: "Bureaux" },
  { id: "rangements", name: "Rangements" },
];

export const sortOptions = [
  { id: "newest", name: "Nouveauté" },
  { id: "price-low", name: "Prix: Bas à Haut" },
  { id: "price-high", name: "Prix: Haut à Bas" },
  { id: "popular", name: "Les plus populaires" },
];
